[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.30.4"
ci = "github"
installers = []
targets = ["x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
checksum = "false"
source-tarball = false
include = ["LICENSE"]